// lib/marketing-data.ts — централни данни за маркетинг страницата

export const CDN = 'https://d1yei2z3i6k35z.cloudfront.net/4263526'
export const AFF = '?tracking=6809eceee15ad'

// ── Афилиейт продукти ───────────────────────────────────────
export const PRODUCTS = [
  {
    id: 'kristalon',
    name: 'Кристалон Зелен 18-18-18',
    badge: 'Най-използван',
    subtitle: 'NPK тор с микроелементи',
    desc: 'Водоразтворим NPK тор — стимулира бърз растеж, силна коренова система и по-голям добив.',
    features: ['100% водоразтворим', 'Съдържа микроелементи', 'За листно торене и фертигация', 'Увеличава добива и качеството'],
    img: `${CDN}/69b0fc97106ef_zelen-kristalon-230x400.webp`,
    link: `https://agroapteki.com/torove/npk-npk-torove/kristalon-zelen-specialen-18-18-18-kompleksen-tor/${AFF}`,
    partner: 'agroapteki',
    color: '#16a34a',
    tag: '⭐ Фермерски фаворит',
  },
  {
    id: 'kaliteh',
    name: 'Калитех',
    badge: 'Анти-гниене',
    subtitle: 'Калциев биостимулатор',
    desc: 'Мощен калциев биостимулатор — доставя лесно усвоим калций и предотвратява върхово гниене.',
    features: ['Предпазва от върхово гниене', 'По-здрави и твърди плодове', 'Увеличава добива', 'Устойчивост към суша'],
    img: `${CDN}/69b1000d9fb83_kaliteh-224x400.webp`,
    link: `https://agroapteki.com/torove/biostimulatori/kaliteh/${AFF}`,
    partner: 'agroapteki',
    color: '#0369a1',
    tag: '🛡️ Защита на плода',
  },
  {
    id: 'amalgerol',
    name: 'Амалгерол',
    badge: 'Легендарен',
    subtitle: 'Биостимулатор за имунитет',
    desc: '100% природен продукт от алпийски билки и морски водорасли — щит срещу стреса.',
    features: ['Мощен анти-стрес ефект', 'Ускорява разграждането', 'Подобрява приема на азот', '100% биоразградим'],
    img: `${CDN}/69b11176b1758_amalgerol-300x400.webp`,
    link: `https://agroapteki.com/torove/techni-torove/amalgerol-za-uskoryavane-rasteja-na-kulturite/${AFF}`,
    partner: 'agroapteki',
    color: '#059669',
    tag: '🌿 100% Природен',
  },
  {
    id: 'sineis',
    name: 'Синейс 480 СК',
    badge: 'Био защита',
    subtitle: 'Инсектицид на основата на спинозад',
    desc: 'Революционен биологичен инсектицид. Спира трипса, Tuta absoluta и колорадския бръмбар за часове.',
    features: ['Ефективен срещу трипс', 'Безмилостен към Tuta absoluta', 'Карантинен срок само 3 дни', 'Устойчив на отмиване'],
    img: `${CDN}/69b4f5319cf6f1.51072214_sineis-20-237x400.webp`,
    link: `https://agroapteki.com/preparati/insekticidi/sineis-480-sk/${AFF}`,
    partner: 'agroapteki',
    color: '#dc2626',
    tag: '🐛 Спира вредителите',
  },
  {
    id: 'ridomil',
    name: 'Ридомил Голд Р ВГ',
    badge: 'Срещу мана',
    subtitle: 'Системен фунгицид',
    desc: 'Легендарен фунгицид — предпазва и лекува вече възникнала зараза. Прониква за 30 минути.',
    features: ['Лечебно действие в 48ч', 'Не се отмива от дъжд', 'Защита на новия прираст', 'Лесна разтворимост'],
    img: `${CDN}/69b4f6e3264510.81149458_ridomil-gold-300x400.webp`,
    link: `https://agroapteki.com/preparati/fungicidi/ridomil-gold/${AFF}`,
    partner: 'agroapteki',
    color: '#7c3aed',
    tag: '🍄 Стопира маната',
  },
  {
    id: 'turbo-root',
    name: 'Турбо Рут',
    badge: 'За вкореняване',
    subtitle: 'Биостимулатор на корените',
    desc: 'Тайното оръжие при засаждане. Стимулира растежа на фините корени с хуминови киселини.',
    features: ['Бързо вкореняване', 'Подобрява почвата около корена', 'Готови аминокиселини', 'Устойчивост към стрес'],
    img: `${CDN}/69b4fd32592803.63113743_turbo-rot-224x400.webp`,
    link: `https://agroapteki.com/torove/biostimulatori/turbo-rut/${AFF}`,
    partner: 'agroapteki',
    color: '#92400e',
    tag: '🌱 100% прихващане',
  },
]
